version: '3'

services:
  chromedriver:
    image: selenium/standalone-chrome-debug:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - '4444:4444'
      - '5900:5900'

  selenium-side-runner:
    build: .
    depends_on: 
     - chromedriver
    volumes:
      - './sides:/sides'
      - './out:/root/out'
